Update for NetBox 4.0.7; Add more logging, error checking; Fix #134, …
minitriga/Netbox-Device-Type-Library-Import pull request #145
Opened 2024-07-11 20:20 UTC by NicJames2378

Verified working with:

- NetBox 4.0.7
  - [hosted in Docker](https://github.com/linuxserver/docker-netbox)
  - Running on CentOS Stream 8
- Python 3.12.4
  - Running under Windows 11 22H2

2024-08-05 16:15 UTC, brandan-schmitz requested changes
I tried running your PR and I encountered a few issues. I outlined what I did to fix those here.

2024-08-05 16:15 UTC, brandan-schmitz commented on settings.py
> +RETRY_DELAY = os.getenv("RETRY_DELAY", default=5) # Configurable for more conjested networks. 5 generally works.
The default needs to be provided as a string. If a user does not supply a value, and it tries to use the default which is already an integer, the `isdigit()` function is not available so it errors out.

```python
RETRY_DELAY = os.getenv("RETRY_DELAY", default="5")
```

2024-08-05 16:15 UTC, brandan-schmitz commented on netbox_api.py
> +                            self.handle.log(f"Error '{exce.error}' creating module type: {curr_mt["manufacturer"]} {curr_mt["model"]} {curr_mt["part_number"]}")
Some things here need to be in single quotes not double:
```python
self.handle.log(f"Error '{exce.error}' creating module type: {curr_mt['manufacturer']} {curr_mt['model']} {curr_mt['part_number']}")
```

2024-08-05 16:25 UTC, brandan-schmitz commented
It also seems that some of the changes for retries upon connection errors is not working 100% as I have had instances where the Netbox server gets temporarily overloaded and returns a 502 connection error and the importer is not catching this and it causes it to crash.

```python
Traceback (most recent call last):
  File "/app/nb-dt-import.py", line 68, in <module>
    main()
  File "/app/nb-dt-import.py", line 30, in main
    netbox.create_device_types(device_types)
  File "/app/netbox_api.py", line 138, in create_device_types
    self.device_types.create_interfaces(device_type["interfaces"], dt.id)
  File "/app/netbox_api.py", line 281, in create_interfaces
    existing_interfaces = {str(item): item for item in self.netbox.dcim.interface_templates.filter(
  File "/app/netbox_api.py", line 281, in <dictcomp>
    existing_interfaces = {str(item): item for item in self.netbox.dcim.interface_templates.filter(
  File "/usr/local/lib/python3.9/site-packages/pynetbox/core/response.py", line 128, in __next__
    next(self.response), self.endpoint.api, self.endpoint
  File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 292, in get
    req = self._make_call(add_params=add_params)
  File "/usr/local/lib/python3.9/site-packages/pynetbox/core/query.py", line 259, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 502 Bad Gateway but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.
```

2024-08-05 17:27 UTC, NicJames2378 commented on settings.py
> +RETRY_DELAY = os.getenv("RETRY_DELAY", default=5) # Configurable for more conjested networks. 5 generally works.
Good find. I've fixed this in my branch. I don't generally use dynamically typed languages, so some of the intricacies are lost on me.

2024-08-05 17:55 UTC, NicJames2378 commented on netbox_api.py
> +                            self.handle.log(f"Error '{exce.error}' creating module type: {curr_mt["manufacturer"]} {curr_mt["model"]} {curr_mt["part_number"]}")
Commit message didn't take for whatever reason. Fixed in commit 3ea22ac. Changed all [" to [' and all "] to ']

2024-08-05 18:20 UTC, NicJames2378 commented
I'm having trouble getting the 502 issue to reproduce on a fresh test environment, so that one may have to wait a week or so for me to get back to my dev environment. To assist me in reproducing, could you provide the NetBox logs from the time around the import? Additionally, can you confirm NetBox is still usable from the web both before and after performing an import? This is to verify that is a connectivity issue to the importer and not an issue in NetBox itself going offline.


As an alternative possibility, it looks like this may possibly be solved by amending netbox_api.py on line 164 to read as `except (http.client.RemoteDisconnected, requests.exceptions.ConnectionError, pynetbox.RequestError) as e:` instead. This will only help if the issue is caused by the connection dropping after the device type is created but _before_ the interfaces/ports/etc are. I didn't account for nor encounter this possibility initially, so it's possible I failed to catch a disconnection.

Let me know if you try the latter, and if it works I'll update the pull request with the new code.

2024-09-20 11:51 UTC, gurubert commented on netbox_api.py
> +                            self.handle.log(f"Error '{exce.error}' creating module type: {curr_mt["manufacturer"]} {curr_mt["model"]} {curr_mt["part_number"]}")
Either have outer ' and inner " or the other way around. But you cannot have something like `f'Processing Source File: {curr_mt['src']}'`

2025-03-11 07:51 UTC, bastianleicht approved these changes
Worked on my end without Problems

2025-11-18 23:09 UTC, closed without merging

2025-11-18 23:11 UTC, NicJames2378 commented
I mistakenly garbled other features into the branch for this PR. To prevent accidently merging unintended code, I have closed this PR.